name: PR Pipeline
on:
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Scan secrets with Gitleaks
      uses: gitleaks/gitleaks-action@v2
      
    - name: Dependency Vulnerability Check
      uses: jeremylong/DependencyCheck@v6.5.0
      with:
        format: 'HTML'
        output-directory: 'dependency-check-report'
        
    - name: Build and run tests with Maven
      run: mvn -B clean verify
      
    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        projectBaseDir: .
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_PROJECT_KEY: bakugo-todos
        SONAR_ORGANIZATION: Bakugo_todos
        
    - name: Wait for Quality Gate
      uses: SonarSource/sonarqube-quality-gate-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
